patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0002-msm_fb-display-exit-properly-when-rotator-max-sessio.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0006-msm_fb-display-update-var-in-display-commit.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0007-msm_fb-hdmi-Resolution-modes-on-HDMI.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0022-msm_fb-display-fix-iommu-page-fault-when-iommu-buffe.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0035-msm_fb-display-fix-iommu-page-fault-when-iommu-buffe.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0036-msm_fb-display-fix-the-hang-issue-caused-by-solidfil.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0038-msm_fb-display-fix-the-suspend-resume-hang-caused-by.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0039-msm_fb-display-wait4vsync-before-set-suspend-flag.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0040-msm_fb-display-Program-source-address-registers-corr.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0043-msm_fb-display-calculate-mdp-clock-including-borderf.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0044-msm_fb-display-add-mutex-to-video_off.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0045-msm_fb-display-Do-clock-control-within-mdp4_hw_init.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0046-msm_fb-Update-MDP-fence-wait-behaviour.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0047-msm_fb-display-balance-secure-map-and-unmap-in-each-.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0048-msm_fb-display-no-native-frame-buffer-memory-operati.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0049-msm_fb-display-Wait-for-DMAE-for-external-interface-.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0050-msm_fb-display-add-mfd-null-pointer-and-mfd-panel_po.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0051-msm_fb-display-reset-base-layer-database.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0052-msm_fb-display-get-mdp-bandwidth-parameters-from-boa.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0053-msm_fb-Fix-adb-shell-start-stop-issue-when-bypass-en.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0055-msm_fb-display-prepare-clocks-before-enable-AHB-cloc.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0056-msm_fb-display-add-one-more-pipe_commit-delay-before.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0057-msm_fb-display-add-mdp-master-port1-bandwidth-reques.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0058-msm_fb-display-balance-bus-bandwidth-on-mdp-axi-port.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0059-msm_fb-display-add-scaling-factor-for-mdp-ab.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0060-msm_fb-display-issue-completion-when-disabling-vsync.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0062-msm_fb-display-Do-a-pre-fill-to-writeback-buffers.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0063-msm_fb-display-free-previous-iommu-buffer-only-at-ov.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0064-msm_fb-Remove-the-extra-freelist-in-display_commit.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0065-msm_fb-display-fix-iommu-page-fault-when-iommu-buffe.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0091-msm_fb-display-keep-a-minimum-mdp-ib-bandwidth-reque.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0159-msm_fb-Set-RR-sched-policy-for-Glupdator-thread.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0214-msm_fb-Correct-R-and-G-offsets-for-correct-mapping.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0215-msm_fb-Increase-base-fence-timeout.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0218-msm_fb-display-Add-pseudo-planar-422-H1V2-support-in.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0219-msm_fb-display-Fix-interleaved-422-input-format-regi.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0234-msm_fb-display-silent-blending-error-warning-message.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0235-msm_fb-display-Add-minimum-src-dst-image-size-valida.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0236-msm_fb-display-add-mdp-new-update-method.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0238-msm_fb-display-Configure-solidfill-color-to-black.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0261-msm_fb-display-get-mipi-frame-rate-from-panel-file.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0262-msm_fb-display-add-mdp-clock-control-to-histogram-en.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0303-msm_fb-Make-sure-MDP-clock-is-ON-during-register-acc.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0415-msm_fb-display-remove-extra-mdp4_dsi_cmd_clk_check.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0416-msm_fb-display-change-TE-simulation-and-read-pointer.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0418-msm_fb-display-add-wfd-clk-ctrl-in-pipe_commit.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0420-msm_fb-display-fix-fence-fd-list-be-put-twice.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0421-msm_fb-display-initialize-dmap_comp-before-wait4dmap.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0422-msm_fb-display-release-mdp-clk-in-mdp4_overlay_write.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0540-msm_fb-hdmi-change-HDMI_PHY_REG1-based-on-foundry.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0541-msm_fb-hdmi-change-HDMI_PHY_REG1-based-on-source.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0544-msm_fb-display-Avoid-dsi-clock-warnings-during-boot.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0545-msm_fb-display-Add-compulsory-wait-after-DTV-s-TG-is.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0668-msm_fb-display-Add-support-to-YCBYCR-MDP-format.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0724-msm-msm_fb-Map-RGB-layers-to-the-max-possible-size.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0725-msm-msm_fb-Do-not-use-ION_IOMMU_UNMAP_DELAYED-flag.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0730-msm_fb-display-Program-TILE-video-frame-size-in-dma-.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0731-msm_fb-display-update-video-tile-framesize-register.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0732-msm-msm_fb-Fix-Regressions-because-of-overmap-change.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/0774-msm_fb-Fix-color-format-mapping-between-V4L2-and-MDP.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/3196-msm_fb-display-get-mdp-bandwidth-parameters-from-boa.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/4846-msm_fb-mdp-Restore-early_suspend-definition-it-cause.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/5204-msm_fb-display-validate-input-args-of-mdp4_argc_proc.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/5611-msm_fb-hdmi-Update-frame-rate-on-resolution-change.patch
patch -p1 -N --verbose --dry-run < /media/root/robcore/android/Alucard-Kernel-jfltexx-my-tw-5.0/patches/msm_fb/5612-msm-display-msm_fb-Fix-hang-when-framework-is-reboot.patch