--- drivers/media/video/msm/sensors/Makefile
+++ drivers/media/video/msm/sensors/Makefile
@@ -17,3 +17,4 @@ obj-$(CONFIG_WEBCAM_OV9726) += ov9726_v4l2.o
 obj-$(CONFIG_OV7692) += ov7692_v4l2.o
 obj-$(CONFIG_VX6953) += vx6953.o
 obj-$(CONFIG_OV9724) += ov9724_v4l2.o
+obj-$(CONFIG_OV5640) += ov5640_v4l2.o
